### ISSUE TITLE
getting 'Indexerror' in train_multi_gpu.py 

### ISSUE THREAD

**Issue by sumeshthakr** [WangYueFt/dgcnn#71]
Getting the following error

Traceback (most recent call last):
  File "train_multi_gpu.py", line 390, in <module>
    train()
  File "train_multi_gpu.py", line 372, in train
    eval_one_epoch(epoch)
  File "train_multi_gpu.py", line 327, in eval_one_epoch
    pointclouds_phs[1]: cur_data[begidx: endidx, ...], 
IndexError: list index out of range

**Comment by pratibhashinde** [comment]
Hi,

Are you able to solve it? I am also facing the same problem.

Thanks.
